# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e716854bb4763fdf48ba34faec0ba15c13d401f4cca1b1b5edee6a5cefaf609ce3f034416f66d5f3fa38ebec852baa20d0c065a542db8ac30ebad877b0ab1bf

test:
  secret_key_base: f0cce702a88518ee3d8eb741a03037b8c8c461b1bf382f3655b6566f533a90fefae6e9996d9dd6da678f2a7fe37fa0125c7c1a493cac41c1b46902bc098441f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
